### ISSUE TITLE
Firefox: No Sub-Elements in Accordion-Headline clickable

### ISSUE THREAD

**Issue by Dreamfish19** [michu2k/Accordion#11]
Hi,

I have the following problem:

As soon as I add ANY HTML tags to "ac-q", I'm not able to click the headline in Firefox anymore.

Please see the following fiddle:

https://jsfiddle.net/dreamfish/va05hdy3/

How to replicate:

Click on "Headline with span" on firefox -> Not opening the accordion.

Click on "Pure Headline" on firefox -> Everything is working fine.

**Comment by michu2k** [comment]
Hi @Dreamfish19 
Add `ac-target` class to the `span` element. In the next update, this option will be modified and will no longer be needed

Cheers

**Comment by Dreamfish19** [comment]
Great, this solves my issue, thanks very much!
