### ISSUE TITLE
Close accordion by clicking element outside the questionClass?

### ISSUE THREAD

**Issue by dubfonik** [michu2k/Accordion#14]
I have an element inside the answerClass (an "X") which, when clicked, I would like to close that accordion. Is this possible?

I am getting an error in console **accordion.min.js?ver=2.8.0:9 Uncaught TypeError: t.className.match is not a function** when clicking this element after applying the targetClass

**Comment by dubfonik** [comment]
Actually I found out the issue: I was trying to use an SVG which didn't seem to receive the click event. Using a PNG instead is fine but it would be good to allow SVG to take this click event

**Comment by michu2k** [comment]
Hi @dubfonik 
In the new version `3.0.0` you can use `.close(idx)` method.
