### ISSUE TITLE
Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by Nadareh** [michu2k/Accordion#2]
Hi there! first off all many thanks for creating this plugin. It helped me a lot. However, the js doesn't work on IE because of an error: "Object doesn't support property or method 'forEach'" really appreciate your help. Thanks!

**Comment by michu2k** [comment]
Thanks for your feedback. I will try to fix this problem as soon as possible.

**Comment by michu2k** [comment]
IE9 is now supported, however we recommend using newest version of browser :)
