### ISSUE TITLE
openOnInit example

### ISSUE THREAD

**Issue by colorful-tones** [michu2k/Accordion#20]
I'm wondering if you can provide an example of how one might use the `openOnInit` option please?

I'm curious if this option allows a designated item to be open on initialization? If that is the case then I'm doubly interested in how your example would look.

I've tried getting the `openOnInit` to work as I understood, but coming up with empty. Here is something I'm working with:

```
import Accordion from 'accordion-js';

/**
 * @module Accordion
 *
 * @description
 *
 * Accordion
 *
 */
export default class Accordions {
	/**
	 * Initialize everything
	 */
	constructor() {
		// Grab all accordions.
		this.accordions = Array.from( document.querySelectorAll( '.accordion-container' ) );

		if ( ! this.accordions.length ) {
			return;
		}

		new Accordion( this.accordions, {
			openOnInit: [ '1' ],
		} );
	}
}
```

Thanks for writing and maintaining this handy component.

**Comment by michu2k** [comment]
Hi @colorful-tones 
An example of `openOnInit` is already on the demo page https://michu2k.github.io/Accordion/. 
You need to pass the numbers to the array :) 

Cheers

**Comment by colorful-tones** [comment]
@michu2k I do not know how I missed that! My powers of observation were very low that day. 

Thanks for the great work and follow through! 👏
