### ISSUE TITLE
How to reinitialization accordion when loading new accordion elements?

### ISSUE THREAD

**Issue by kit52** [michu2k/Accordion#32]
I have many accordions on page, and all init when page load. And i have load button in every him, when i load new accordion items with server and add him to work accrodion? this items not work, You have methods for this situation?

**Comment by RichForever** [comment]
I'm looking for solution too :)

**Comment by michu2k** [comment]
Hi guys
I'll figure out how to do it and let you know when I get the results :)

**Comment by michu2k** [comment]
Hi, I released a new version 3.2.0 which includes a .update() method. Every time you load new items, you need to update your Accordion instance as below: 

```javascript
const accordion = new Accordion(options)

function loadMore() {
   // load more items..
   // add items to the accordion container
   accordion.update()
}
```

![NZDOm5gKbP](https://user-images.githubusercontent.com/22056149/159119946-76d9b08a-822f-4f26-b757-96ad56dd98bb.gif)

**Comment by RichForever** [comment]
@michu2k This is what I needed. Now it's working like it should :)

**Comment by kit52** [comment]
> 

Hi! This is a very useful method, but you can also add an element, as I wrote in the message above. For example, when you have 20 accordions on a page, and they all have the same layout. How can I figure out which accordion needs to be updated from the array of these dependencies? I added the element as I wrote above and then you can compare it with the note in which the event occurs so that only a specific accordion can be updated.

**Comment by michu2k** [comment]
@kit52 I'm not going to add any additional elements to the core for now, but thanks for the suggestion. Regards.
