### ISSUE TITLE
Adding/removing an attribute from the button + edit the general structure

### ISSUE THREAD

**Issue by SineYlo** [michu2k/Accordion#33]
Hi!

I noticed that in your solution, the button does not have the type attribute with the button value. This is not quite correct because by default the button tries to send data to the server because the type attribute with the value submit is set. I recommend redefining this by adding the following to the button — `type="button"`.

I also don't quite understand why the `role` attribute with the `button` value is set to the button. The button is calculated with this value by default. It's just redundant code.

Another point about the structure of the accordion itself. You have it made with the help of tags — `div`. But in terms of accessibility, this is not the best option. It is best to do this with a list — `ul > li`. Since when a person starts the screen reader, he will be told — “This is a list with a certain number of elements.”

I would also recommend replacing the `h2` header with `h3`. Because it often happens that h2 is used as the header of some section.

And so, in general, the accordion turned out to be really cool! At least I am glad that this is not another solution using jQuery. :)

**Comment by michu2k** [comment]
Hi @SineYlo 
Thanks for your feedback. The Accordion structure is not hard-coded and should be defined by the programmer himself. So if you want to use h3 tags instead of h2 or li instead of div, you **can** do that. As for the button role = "button" - Again you don't need to use a button here, you can use span or div or whatever you want.

Cheers

**Comment by SineYlo** [comment]
@michu2k 
In general, everything is clear on the last points, but I would still think about the first point about `type="button"`. For not all people know this.
Anyway, thanks for the answer!

**Comment by michu2k** [comment]
I will add this to the example in the README
