### ISSUE TITLE
Missing CDN link to js file in demo page

### ISSUE THREAD

**Issue by Pustur** [michu2k/Accordion#40]
[In the demo website](https://michu2k.github.io/Accordion/) the CDN links are the same, both pointing to the css file.

I think you meant to put the js file there:

https://unpkg.com/accordion-js@3.2.0/dist/accordion.min.js

I'd like to fix this myself but I don't think there are the necessary files to build the website in the repo currently.

**Comment by michu2k** [comment]
Thanks! I must have missed it. I'll fix it today

**Comment by michu2k** [comment]
Fixed
