### ISSUE TITLE
Remove constraint that accordion items must be direct children of the accordion container

### ISSUE THREAD

**Issue by Pustur** [michu2k/Accordion#41]
Hey, sorry to bother you again.

I run into a problem with this layout:

![layout](https://user-images.githubusercontent.com/13663338/161272764-165a8299-2e9f-4148-b4c0-ddb341ae05fd.png)

Basically I need to separate the accordion into columns, but the accordion should still work as one piece.

I found that inserting an elment between the container `.accordion-container` and the items `.ac` breaks the accordion functionality.

[JSFiddle to show the problem](https://jsfiddle.net/pjk5gmrs/)

My proposal would be to allow the user to define a selector to target the items, something like this:

```js
new Accordion('.accordion-container', {
  // Feature proposal
  childrenSelector: '.ac'
});
```

What do you think? Is it doable?

Thanks for your time,
Loris

**EDIT:** or maybe we could use the value of `elementClass` to target the children? Just sharing some ideas.

**EDIT2:** I made some changes in my fork:

- [branch - code-review](https://github.com/Pustur/Accordion/tree/code-review) is more for small refactors that I found while reading the code
- [branch - new-feature](https://github.com/Pustur/Accordion/tree/new-feature) is a potential implementation to fix this issue

you can take a look and if you want I can submit them as pull requests :)

**Comment by michu2k** [comment]
Hi @Pustur 
Thanks for the suggestions, but for now I'm not going to make any changes to the Accordion structure and the implementation you suggest can break the nested functionality of the accordion. However, I will check to see if this can be easily implemented. For now, to create a similar layout as on the image, you can try to use the CSS grid, although I cannot be sure that you will be satisfied with the effect. 🤔 
 
As for the code-review branch with the JSDoc update and other stuff, this one looks good for me, so you can create a pull request and I will check and test all the changes and publish a new release in my spare time.

Thanks for the contribution :)

**Comment by Pustur** [comment]
Hi @michu2k,

You're right, I forgot about the nested feature and my change definitely breaks it.

I already tried a workaround with CSS grid but unfortunately it has some problems and limitations so it's not an optimal solution in my case.

**Comment by michu2k** [comment]
Hey, quick info. 
At the moment I am working on an additional option that will allow getting all the items inside the defined container.

**Comment by michu2k** [comment]
In v3.3.0 the `onlyChildNodes` option is what you are looking for. Please note that disabling this feature will break the functionality of the nested accordions, but it was a reasonable fix I found.

**Comment by Pustur** [comment]
Thank you so much for this feature! ❤️  
I will try it next week on the component mentioned above.

**Comment by Pustur** [comment]
@michu2k Can confirm it works perfectly in my use case, thanks again :)
