### ISSUE TITLE
method Update

### ISSUE THREAD

**Issue by kit52** [michu2k/Accordion#43]
After applying the Update method, the first loaded element opens. Is this the expected behavior?

**Comment by michu2k** [comment]
Hi
During the tests, I didn't notice any similar problems that you describe. Can you provide more information on your use case?

**Comment by kit52** [comment]
> Hi During the tests, I didn't notice any similar problems that you describe. Can you provide more information on your use case?

Im inited acc on page this code
` const accordionNewItems = [...document.querySelectorAll('.accordion')]
  const initedAccordionsItems = accordionNewItems.filter(acc => !acc.classList.contains('not-inited'))
  const notInitedAccordionsItems = accordionNewItems.filter(acc => acc.classList.contains('not-inited') && !acc.classList.contains('search-form__specialization-accordion'))

  initedAccordions = new Accordion(initedAccordionsItems, {
    elementClass: 'accordion__item',
    triggerClass: 'accordion__head',
    panelClass: 'accordion__content',
    activeClass: 'active',
    openOnInit: [0],
    onOpen: (item) => {

      const header = document.querySelector('header')
      const instanceFromTop = item.getBoundingClientRect().top + window.pageYOffset - header.offsetHeight;
      window.scroll({
        top: instanceFromTop,
        left: 0,
        behavior: 'smooth'
      });
    }
  })`
After on page when user click showMore i start this function 
`export function getPriceFromApi(url, btnMore) {
    const parentSection = btnMore.parentNode;
    getData(url).then((res) => {
        if (res.data.prices) {
            btnMore.insertAdjacentHTML('beforebegin', res.data.prices)
            btnMore.style = "display:none;";
            if (res.data.url) {
                btnMore.setAttribute('data-url', res.data.url)
                btnMore.setAttribute('data-count', res.data.count)
                btnMore.style = "display:inline-block;";
            }
            const accordions = [...parentSection.querySelectorAll('.accordion')];
            const parentAccordion = initedAccordions.find(item => item.element == parentSection);
            const initedAccordionsElements = initedAccordions.map(item => item.element)

            const notInitedAccorions = accordions.filter(item => !initedAccordionsElements.includes(item))
            if (notInitedAccorions.length > 0) {
                const newAccordionsInited = new Accordion(notInitedAccorions, {
                    elementClass: 'accordion__item',
                    triggerClass: 'accordion__head',
                    panelClass: 'accordion__content',
                    activeClass: 'active',
                    onOpen: (item) => {
                        const header = document.querySelector('header')
                        const instanceFromTop = item.getBoundingClientRect().top + window.pageYOffset - header.offsetHeight;
                        window.scroll({
                            top: instanceFromTop,
                            left: 0,
                            behavior: 'smooth'
                        });
                    }
                })
                initedAccordions.push(...newAccordionsInited)
            }
            parentAccordion.update()
        }
    })

}`

**Comment by kit52** [comment]
` this.elements
                .filter((element) => !element.classList.contains(`js-enabled`))
                .map((element, idx) => {
                    // When JS is enabled, add the class to the element
                    element.classList.add('js-enabled');

                    this.generateIDs(element);
                    this.setARIA(element);
                    this.setTransition(element);
                    console.log(` элементы массива`);
                    console.log(element);
                    console.log(` includes`);
                    console.log(openOnInit.includes(idx));
                    uniqueId++;
                    return openOnInit.includes(idx) ? this.showElement(element, false) : this.closeElement(element, false);
                });`

in this  you start openOnInit.includes(idx). This always be true for first added element

**Comment by michu2k** [comment]
Yea, you have right. I will fix it this week

**Comment by michu2k** [comment]
Fixed in v3.3.0
