### ISSUE TITLE
Responsive initialization

### ISSUE THREAD

**Issue by ooksanen** [michu2k/Accordion#44]
Would it be possible to add a setting for responsive initialization depending on viewport (or container) width? Something like
```
new Accordion('.accordion-container', {
  responsive: {
    operator: '<',
    viewPort: 640
  }
});
```
or
```
new Accordion('.accordion-container', {
  responsive: {
    operator: '>=',
    viewPort: 1024
  }
});
```
or similar which would init the accordion for screen size < 640px or >= 1024px. That way you could have, for example, the accordion active only for mobile screens where you have limited screen space, but not on desktop, or vice versa.

I tried to implement something like this with resizeObserver by initializing the Accordion if container width is less than n px and destroy() if wider, but I couldn't quite figure out how to get it working properly.

**Comment by michu2k** [comment]
Hi @ooksanen 
Responsive initialization is something you have to do on your side. You can do something similar to this: 

```javascript
window.addEventListener('resize', () => {
    if (window.innerWidth < 768) {
      accordion.attachEvents();
      accordion.closeAll();
    } else {
      accordion.detachEvents();
      accordion.openAll();
    }
  })
```

**Comment by ooksanen** [comment]
Thanks for your reply! I ended up solving my issue pretty much like that, but with resizeObrerver which has a few advantages (depending on the use case) compared to event listener. Here's the relevant part of my solution in case someone else is looking to do the same:
```
const accordion = new Accordion('.accordion-container', {});

const observer = new ResizeObserver(entries => {
	const isSmall = entries[0].contentRect.width < 640;
	if( isSmall ) {
		accordion.update();
		accordion.attachEvents();
	}
	else {
		accordion.destroy();
	}

})

observer.observe('.accordion-container');
```
For some reason the accordion didn't work properly when using only `attachEvents()` and `detachEvents()` methods. Possibly due to my somewhat complex structure and accordions not being the direct children of container, using the new `onlyChildNodes` parameter.

**Comment by Pustur** [comment]
Just adding this as additional info.
Another potential solution would be to use [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) if you wanted to change the accordion based on the viewport.

```js
const mediaQuery = window.matchMedia('(max-width: 600px)');

function mediaQueryHandler(e) {
  if (e.matches) {
    // the viewport is 600 pixels wide or less
  } else {
    // the viewport is more than 600 pixels wide
  }
}

mediaQuery.addListener(mediaQueryHandler);
```
