### ISSUE TITLE
An option to disable default styling.

### ISSUE THREAD

**Issue by Eliasyoussef47** [michu2k/Accordion#45]
I would like an option to disable the default styling of the accordion. I just want this package to facilitate the collapsing and opening. I want to be able to style the elements freely.

**Comment by michu2k** [comment]
Hi @Eliasyoussef47 
Just don't include the CSS file in your project and you won't have any default styling.

Cheers

**Comment by Eliasyoussef47** [comment]
Thanks for replying.
I tried that already but it made the content always displayed (never hidden)

**Comment by michu2k** [comment]
You can copy the styles from this file https://github.com/michu2k/Accordion/blob/master/src/accordion.scss and remove unnecessary styling. You can surely remove the `.ac-text`, `.ac-header` and `.ac-trigger` classes and styles from the `.ac` class.

**Comment by Eliasyoussef47** [comment]
Thanks.
I've already implemented an accordion using a different package so I won't be testing this but I trust it will.
