### ISSUE TITLE
Issues with `closeAll()` method

### ISSUE THREAD

**Issue by turnstylerj** [michu2k/Accordion#47]
When using the `closeAll()` method on an existing accordion, I'm noticing a couple of issues:
1. A previously-registered `onClose` function on the accordion doesn't fire.
2. The close transition for any open accordion folds doesn't happen, and the open fold just disappears instantly.

Both of these issues do not occur if I close a specific fold like `close(0)`, but only with `closeAll()`.

**Comment by geouser** [comment]
And also, the `aria-expanded="true"` attribute on the `.ac-trigger` element does not change to `false`

**Comment by michu2k** [comment]
Hi
Thanks for reporting the bugs. The `closeAll()` animation is disabled by default, but I can certainly add an additional param to enable animation. And when it comes to bugs, I will try to fix them as soon as possible.

**Comment by michu2k** [comment]
Hi. I have fixed the bugs mentioned above, and if you need a closing animation when closing all elements, then you can write your own implementation:

```javascript
  closeAllBtn.addEventListener('click', () => {
    const accordionElements = document.querySelectorAll(".ac");

    [...accordionElements].forEach((element, idx) => {
      const isActive = element.classList.contains('is-active');

      if (isActive) {
        accordion.close(idx);
      }
    })
  })
```
