### ISSUE TITLE
Any way to make the accordion open upwards?

### ISSUE THREAD

**Issue by AdrianGzzEsc** [michu2k/Accordion#49]
Hello, I would like to know if theirs the ability to open the accordion upwards instead of downwards.

**Comment by michu2k** [comment]
Hi @AdrianGzzEsc 

Yeah, it is possible by modifying accordion styles. Add this code below to your `.ac` class (or create an additional class) and it should work.

``` 
  display: flex;
  flex-direction: column-reverse;
```
