### ISSUE TITLE
Active State after 'openOnInit'

### ISSUE THREAD

**Issue by marianohsn** [michu2k/Accordion#58]
I'm passing the option: `openOnInit: [2]` in order to show the third accordion item expanded by default, but its corresponding header/button's **style remains in collapsed state**.

How can I make the header style change accordingly to expanded state when using `openOnInit: []`?

_Incorrect state of third header after being triggered by `openOnInit: [2]`:_
![Screen Shot 2023-02-21 at 10 58 21 AM](https://user-images.githubusercontent.com/68350580/220423443-6763d0fe-03ed-4b62-b150-4c595a49beb9.jpg)

_Correct state of third header after being triggered by user click:_
![Screen Shot 2023-02-21 at 10 58 28 AM](https://user-images.githubusercontent.com/68350580/220423680-1c68df66-d66e-4b17-b80b-8bed1330eda0.jpg)

**Comment by michu2k** [comment]
Hi @marianohsn 
The applied styles are correct. The difference between the first and second images is that the :focus styles are applied to the second image because the item you clicked is focused.

```css
    .ac-trigger:focus {
      color: $color-grey;
    }
```

**Comment by marianohsn** [comment]
Hello @michu2k - Thank you for your reply

Shouldn't the `openOnInit: [X]` function also change the corresponding header/button to its  _focused_  state when triggered? I assumed that woud be the logical behaviour.

Otherwise, I could try simulating a click, or altering the style of the expanded header via JS.

**Comment by michu2k** [comment]
I checked the official W3 accordion demo and it looks like they are doing exactly the same, applying styles to the currently focused element. I would say that using the same styles for the focus state and the open state can be a bit confusing for someone who uses Tab for navigation.

> Otherwise, I could try simulating a click, or altering the style of the expanded header via JS.

You can just add an additional className and manage the styles via CSS or modify `activeClass` property.
