### ISSUE TITLE
Initialising multiple accordions on one page

### ISSUE THREAD

**Issue by Flowgram** [michu2k/Accordion#7]
Hi there, 

How would I go about initialising multiple accordions on one page that would share the same options?

Many thanks!

**Comment by Flowgram** [comment]
I ended up solving this by adding an ID to each one and then initialising each based on that:

    const accordions = Array.from(document.querySelectorAll('.accordion'));

    if (accordions) {
      let count = 0;
      let id = null;

      accordions.forEach(item => {
        id = 'accordion' + count;
        item.id = id;

        new Accordion('#' + id, {
          duration: 300,
          elementClass: 'element',
          questionClass: 'question',
          answerClass: 'answer'
        });
        count++;
      });
    }

**Comment by michu2k** [comment]
Hi @Flowgram 
It's nice to see, that you've solved your problem 
Greetings

**Comment by Fcog** [comment]
it would be nice if multiple accordions in one single page could start with the same class without doing that tricky initialization
`new Accordion( '.js-accordion' )`

**Comment by Preen** [comment]
+1
