### ISSUE TITLE
Accordions not expanding consistently (on mobile)

### ISSUE THREAD

**Issue by ksvhlm** [michu2k/Accordion#73]
Hello, I've been trying to get this to work for a while now, the accordions are only active on mobile (I manually copied the accordion-js css file and wrapped everything in a media query), but using the responsive mode on a browser, I cannot open the accordions, and on mobile, they stop working if you scroll upwards and press an accordion, like they get clicked twice at the same time

[The page in question](https://dearbaby.dk/baeredygtig-legetoej/)

The only active setting for the accordions is showMultiple: true

**Comment by ksvhlm** [comment]
I added the attachEvents and closeAll methods to my code and it looks like this, but nothing changed on the frontend, is there any reason why it wouldn't work like this, or do I have to detach the events on desktop still, even if I only load on mobile?
`
jQuery(document).ready(function ($) {
  $(window)
    .on('resize', function () {
      // Enable accordions on tablet/mobile
      if (window.matchMedia('(max-width: 991px)').matches) {
        const accordions = Array.from(
          document.querySelectorAll(
            '.dearbaby-builder-container.accordion-container'
          )
        )
        new Accordion(accordions, {
          showMultiple: true
        })
        accordion.attachEvents()
        accordion.closeAll()
      }
    })
    .resize()
})
`

**Comment by michu2k** [comment]
You may have to try something like this:

```js
jQuery(document).ready(function ($) {

  const accordions = Array.from(
    document.querySelectorAll('.dearbaby-builder-container.accordion-container' )
  );

  const accordion = new Accordion(accordions, {
     showMultiple: true
  });

  // Initial check (disable the accordion if it is desktop view)
  if (!window.matchMedia('(max-width: 991px)').matches) {
    accordion.detachEvents();
    accordion.openAll();
  }

  $(window)
    .on('resize', function () {
      // Enable accordions on tablet/mobile
      if (window.matchMedia('(max-width: 991px)').matches) {
        accordion.attachEvents();
        accordion.closeAll();
      }
    })
    .resize()
})
```

**Comment by michu2k** [comment]
Ok, I think I know where the problem is. You're trying to initialize the accordion in the `resize` function, so when you turn on the mobile view and try to open the accordion, it won't open because the viewport hasn't resized, so the accordion hasn't been initialized yet.

You need to initialize the accordion outside the resize function. It will look more or less like this:

```js
jQuery(document).ready(function ($) {
  if (window.matchMedia('(max-width: 991px)').matches) {

    const accordions = Array.from(
      document.querySelectorAll('.dearbaby-builder-container.accordion-container' )
    );

    const accordion = new Accordion(accordions, {
       showMultiple: true
    });
  }
})
```

**Comment by ksvhlm** [comment]
Oh that worked perfectly, thanks :)
Didn't think to move the code outside of the resize function, because that's my usual go-to for resize compatibility on WordPress 👍
